Adding support for different target host than the executing environment
wayfair-incubator/forker pull request #255
Opened 2023-06-23 20:00 UTC by rajbos

## Description

See the description in #254 as well. We use this on action on our private GitHub Enterprise Server to fork actions on github.com. Since the action runs in the local context by default, we need to make some changes to support this. This PR adds a new optional parameter to support targeting a different environment. If the variable is empty, the current behavior is still the same: it uses the current environment from `actions/core`.

If the new parameter `targetInstanceUrl` is set, it will configure Octokit with that parameter. The rest of the code is the same.

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/forker/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-09-18 09:31 UTC, rajbos commented
@lelia anything I can do to help with this? I can confirm it works as intended on our internal environment 🤗.

2023-10-11 17:04 UTC, lelia requested changes
@rajbos Sorry for the delay here, I haven't worked at Wayfair since the start of the year, so my primary focus has been on other OSS projects at my new company 😔

While I haven't had a chance to explicitly test out the parameter using a GHE instance yet, the overall changes LGTM. My one ask would be that you document the new parameter in the `README` [Inputs](https://github.com/wayfair-incubator/forker#inputs) section following the same pattern as other params (so, datatype, required/not, description, and example input). 

Bonus points if you expand the [Usage](https://github.com/wayfair-incubator/forker#usage) section to include a code snippet for how one would construct this action to target a dummy GHE instance. Thanks and apologies again for the wait!

2023-10-11 17:06 UTC, lelia commented
BTW, feel free to update this PR description to say something like "Fixes #254" so that the related issue will auto-close once this PR merges!

2024-03-02 20:37 UTC, rajbos commented
@lelia : requested changes have been added, please review.

2024-03-13 17:57 UTC, lelia commented on README.md
> +Create a fork in your own GitHub Enterprise Server:
```suggestion
### Target a GitHub Enterprise Server

Create a fork in your own GitHub Enterprise Server:
```

2024-03-13 17:59 UTC, lelia approved these changes
Changes LGTM! Thanks again for the contribution & your patience 🙂

2024-03-13 18:02 UTC, lelia commented on README.md
> +This parameter can be used to target a GitHub Enterprise Server instance instead of https://github.com.
```suggestion
This parameter can be used to target a GitHub Enterprise Server instance instead of <https://github.com>.
```

2024-03-13 18:03 UTC, merged